
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install requirements
        run: sudo apt install -y git curl build-essential libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl mercurial bzr ecj cvs unzip

      - name: Download zip
        run: |
          mkdir Downloads && cd Downloads/
          wget https://downloads.openwrt.org/releases/22.03.2/targets/ramips/mt76x8/openwrt-sdk-22.03.2-ramips-mt76x8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar -Jxf openwrt-sdk-22.03.2-ramips-mt76x8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-22.03.2-ramips-mt76x8_gcc-11.2.0_musl.Linux-x86_64 OpenWrt
          rm -rf openwrt-sdk-22.03.2-ramips-mt76x8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
      - name: feeds update
        run: cd Downloads/OpenWrt && ./scripts/feeds update -a && ./scripts/feeds install libpcap


      - name: Run a one-line script
        run: chmod +x .github/workflows/diy.sh && .github/workflows/diy.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - uses: actions/upload-artifact@v3
        with:
          name: mentohust.zip
          path: Downloads/OpenWrt/bin/packages/mipsel_24kc/base/mentohust*
      - uses: actions/upload-artifact@v3
        with:
          name: libpcap.zip
          path: Downloads/OpenWrt/bin/packages/mipsel_24kc/base/libpcap*
      - uses: actions/upload-artifact@v3
        with:
          name: luci-app-openclash.zip
          path: Downloads/OpenWrt/bin/packages/mipsel_24kc/base/luci-app-openclash*
    
