
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: chmod +x .github/workflows/diy.sh && .github/workflows/diy.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - uses: actions/upload-artifact@v3
        with:
          name: mentohust.ipk
          path: Downloads/OpenWrt/bin/packages/mipsel_24kc/base/mentohust*
      - uses: actions/upload-artifact@v3
        with:
          name: libpcap.ipk
          path: Downloads/OpenWrt/bin/packages/mipsel_24kc/base/libpcap*
      - uses: actions/upload-artifact@v3
        with:
          name: luci-app-mentohust.ipk
          path: Downloads/OpenWrt/bin/packages/mipsel_24kc/base/luci-app-mentohust*
    
