
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: .github/workflows/diy.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Create release
        id: release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.DATE }} 常用ipk
          allowUpdates: true
          tag: ${{ env.FILE_NAME }}
          commit: main
          token: ${{ secrets.RELEASES_TOKEN }}
          body: |
          artifacts: bin/packages/mipsel_24kc/base/*
    
